name: Go

on:
  push:
    tags:
      - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.15.x,1.16.x]
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
  build:
    strategy:
      matrix:
        go-version: [ 1.13.x,1.14.x,1.15.x, 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup SPV Server
        run: docker-compose up -d
      - name: Wait Server to be ready
        run: sleep 5
      - name: Unit Tests
        run: make test-unit
      - name: Integration Tests
        run: go test -race -v -tags=integration ./...
      - name: Build Rest Example
        run: go build ./example/rest
      - name: Build Websocket Example
        run: go build ./example/websocket

  release:
    needs: [golangci,build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}